/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/BoatClasses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatClassDto"][];
                        "application/json": components["schemas"]["BoatClassDto"][];
                        "text/json": components["schemas"]["BoatClassDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBoatClassRequest"];
                    "text/json": components["schemas"]["CreateBoatClassRequest"];
                    "application/*+json": components["schemas"]["CreateBoatClassRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatClassDto"];
                        "application/json": components["schemas"]["BoatClassDto"];
                        "text/json": components["schemas"]["BoatClassDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/BoatClasses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatClassDto"];
                        "application/json": components["schemas"]["BoatClassDto"];
                        "text/json": components["schemas"]["BoatClassDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBoatClassRequest"];
                    "text/json": components["schemas"]["UpdateBoatClassRequest"];
                    "application/*+json": components["schemas"]["UpdateBoatClassRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatClassDto"];
                        "application/json": components["schemas"]["BoatClassDto"];
                        "text/json": components["schemas"]["BoatClassDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Boats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatDto"][];
                        "application/json": components["schemas"]["BoatDto"][];
                        "text/json": components["schemas"]["BoatDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBoatRequest"];
                    "text/json": components["schemas"]["CreateBoatRequest"];
                    "application/*+json": components["schemas"]["CreateBoatRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatDto"];
                        "application/json": components["schemas"]["BoatDto"];
                        "text/json": components["schemas"]["BoatDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Boats/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatDto"];
                        "application/json": components["schemas"]["BoatDto"];
                        "text/json": components["schemas"]["BoatDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateBoatRequest"];
                    "text/json": components["schemas"]["UpdateBoatRequest"];
                    "application/*+json": components["schemas"]["UpdateBoatRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatDto"];
                        "application/json": components["schemas"]["BoatDto"];
                        "text/json": components["schemas"]["BoatDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Boats/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate statistics for a boat across all its sessions and races. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BoatStatsDto"];
                        "application/json": components["schemas"]["BoatStatsDto"];
                        "text/json": components["schemas"]["BoatStatsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    year?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseSummaryDto"][];
                        "application/json": components["schemas"]["CourseSummaryDto"][];
                        "text/json": components["schemas"]["CourseSummaryDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCourseRequest"];
                    "text/json": components["schemas"]["CreateCourseRequest"];
                    "application/*+json": components["schemas"]["CreateCourseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseDto"];
                        "application/json": components["schemas"]["CourseDto"];
                        "text/json": components["schemas"]["CourseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseDto"];
                        "application/json": components["schemas"]["CourseDto"];
                        "text/json": components["schemas"]["CourseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCourseRequest"];
                    "text/json": components["schemas"]["UpdateCourseRequest"];
                    "application/*+json": components["schemas"]["UpdateCourseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseDto"];
                        "application/json": components["schemas"]["CourseDto"];
                        "text/json": components["schemas"]["CourseDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Marks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    activeOn?: string;
                    activeOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MarkDto"][];
                        "application/json": components["schemas"]["MarkDto"][];
                        "text/json": components["schemas"]["MarkDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateMarkRequest"];
                    "text/json": components["schemas"]["CreateMarkRequest"];
                    "application/*+json": components["schemas"]["CreateMarkRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MarkDto"];
                        "application/json": components["schemas"]["MarkDto"];
                        "text/json": components["schemas"]["MarkDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Marks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MarkDto"];
                        "application/json": components["schemas"]["MarkDto"];
                        "text/json": components["schemas"]["MarkDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateMarkRequest"];
                    "text/json": components["schemas"]["UpdateMarkRequest"];
                    "application/*+json": components["schemas"]["UpdateMarkRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MarkDto"];
                        "application/json": components["schemas"]["MarkDto"];
                        "text/json": components["schemas"]["MarkDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RaceDto"][];
                        "application/json": components["schemas"]["RaceDto"][];
                        "text/json": components["schemas"]["RaceDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/races/{raceNumber}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RaceDetailDto"];
                        "application/json": components["schemas"]["RaceDetailDto"];
                        "text/json": components["schemas"]["RaceDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PatchRaceRequest"];
                    "text/json": components["schemas"]["PatchRaceRequest"];
                    "application/*+json": components["schemas"]["PatchRaceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RaceDto"];
                        "application/json": components["schemas"]["RaceDto"];
                        "text/json": components["schemas"]["RaceDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/sessions/{sessionId}/races/{raceNumber}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: number | string;
                    to?: number | string;
                };
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PositionDto"][];
                        "application/json": components["schemas"]["PositionDto"][];
                        "text/json": components["schemas"]["PositionDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/races/{raceNumber}/wind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: number | string;
                    to?: number | string;
                };
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WindDto"][];
                        "application/json": components["schemas"]["WindDto"][];
                        "text/json": components["schemas"]["WindDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/races/{raceNumber}/speed-through-water": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: number | string;
                    to?: number | string;
                };
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SpeedThroughWaterDto"][];
                        "application/json": components["schemas"]["SpeedThroughWaterDto"][];
                        "text/json": components["schemas"]["SpeedThroughWaterDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/races/{raceNumber}/depth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: number | string;
                    to?: number | string;
                };
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepthDto"][];
                        "application/json": components["schemas"]["DepthDto"][];
                        "text/json": components["schemas"]["DepthDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/races/{raceNumber}/temperature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: number | string;
                    to?: number | string;
                };
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TemperatureDto"][];
                        "application/json": components["schemas"]["TemperatureDto"][];
                        "text/json": components["schemas"]["TemperatureDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/races/{raceNumber}/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: number | string;
                    to?: number | string;
                };
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoadDto"][];
                        "application/json": components["schemas"]["LoadDto"][];
                        "text/json": components["schemas"]["LoadDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/races/{raceNumber}/shift-angles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: number | string;
                    to?: number | string;
                };
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ShiftAngleDto"][];
                        "application/json": components["schemas"]["ShiftAngleDto"][];
                        "text/json": components["schemas"]["ShiftAngleDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/races/{raceNumber}/start-line-length": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StartLineLengthDto"];
                        "application/json": components["schemas"]["StartLineLengthDto"];
                        "text/json": components["schemas"]["StartLineLengthDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/races/{raceNumber}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RaceSummaryDto"];
                        "application/json": components["schemas"]["RaceSummaryDto"];
                        "text/json": components["schemas"]["RaceSummaryDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                    raceNumber: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Sessions/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SessionDetailDto"];
                        "application/json": components["schemas"]["SessionDetailDto"];
                        "text/json": components["schemas"]["SessionDetailDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    boatId?: number | string;
                    courseId?: number | string;
                    year?: number | string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SessionSummaryDto"][];
                        "application/json": components["schemas"]["SessionSummaryDto"][];
                        "text/json": components["schemas"]["SessionSummaryDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SessionDetailDto"];
                        "application/json": components["schemas"]["SessionDetailDto"];
                        "text/json": components["schemas"]["SessionDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PatchSessionRequest"];
                    "text/json": components["schemas"]["PatchSessionRequest"];
                    "application/*+json": components["schemas"]["PatchSessionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SessionDetailDto"];
                        "application/json": components["schemas"]["SessionDetailDto"];
                        "text/json": components["schemas"]["SessionDetailDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/Stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global statistics across all boats, sessions, and races.
         * @description Returns aggregate totals for the entire dataset: session and race counts, total sailed distance, top speed, and the date range of recorded sessions. Intended as a high-level overview for dashboards and AI-generated insight reports.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GlobalStatsDto"];
                        "application/json": components["schemas"]["GlobalStatsDto"];
                        "text/json": components["schemas"]["GlobalStatsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BoatClassDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            /** Format: double */
            lengthOverAll: null | number | string;
            /** Format: double */
            beam: null | number | string;
            /** Format: double */
            weight: null | number | string;
            /** Format: double */
            bowspritLength: null | number | string;
            /** Format: date-time */
            createdAt: string;
            sails: components["schemas"]["SailDto"][];
        };
        BoatClassSummaryDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            /** Format: double */
            lengthOverAll: null | number | string;
            /** Format: double */
            beam: null | number | string;
            /** Format: double */
            weight: null | number | string;
            /** Format: double */
            bowspritLength: null | number | string;
        };
        BoatDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            sailNumber: null | string;
            boatClass: components["schemas"]["BoatClassSummaryDto"];
            description: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        BoatStatsDto: {
            /** Format: int32 */
            boatId: number | string;
            boatName: string;
            sailNumber: null | string;
            boatClass: components["schemas"]["BoatClassSummaryDto"];
            /** Format: int32 */
            sessionCount: number | string;
            /** Format: int32 */
            raceCount: number | string;
            /** Format: double */
            totalSessionDurationSeconds: number | string;
            /** Format: double */
            totalRaceDurationSeconds: number | string;
            /** Format: double */
            totalSailedDistanceMeters: number | string;
            /** Format: float */
            topSpeedOverGround: number | string;
        };
        CourseDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            /** Format: int32 */
            year: number | string;
            description: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: double */
            totalLengthMeters: number | string;
            legs: components["schemas"]["CourseLegDto"][];
        };
        CourseLegDto: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            markId: number | string;
            markName: string;
            /** Format: int32 */
            sortOrder: number | string;
            legName: null | string;
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
        };
        CourseLegRequest: {
            /** Format: int32 */
            markId: number | string;
            legName: null | string;
        };
        CourseSummaryDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            /** Format: int32 */
            year: number | string;
            description: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int32 */
            legCount: number | string;
        };
        CreateBoatClassRequest: {
            name: string;
            /** Format: double */
            lengthOverAll: null | number | string;
            /** Format: double */
            beam: null | number | string;
            /** Format: double */
            weight: null | number | string;
            /** Format: double */
            bowspritLength: null | number | string;
            sails: components["schemas"]["SailRequest"][];
        };
        CreateBoatRequest: {
            name: string;
            sailNumber: null | string;
            /** Format: int32 */
            boatClassId: number | string;
            description: null | string;
        };
        CreateCourseRequest: {
            name: string;
            /** Format: int32 */
            year: number | string;
            description: null | string;
            legs: components["schemas"]["CourseLegRequest"][];
        };
        CreateMarkRequest: {
            name: string;
            /** Format: date */
            activeFrom: string;
            /** Format: date */
            activeUntil: null | string;
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
            description: null | string;
        };
        DepthDto: {
            /** Format: date-time */
            time: string;
            /** Format: float */
            depth: number | string;
        };
        GlobalStatsDto: {
            /** Format: int32 */
            totalBoats: number | string;
            /** Format: int32 */
            totalSessions: number | string;
            /** Format: int32 */
            totalRaces: number | string;
            /** Format: double */
            totalSessionDurationSeconds: number | string;
            /** Format: double */
            totalRaceDurationSeconds: number | string;
            /** Format: double */
            totalSailedDistanceMeters: number | string;
            /** Format: float */
            topSpeedOverGround: number | string;
            /** Format: date-time */
            earliestSessionAt: null | string;
            /** Format: date-time */
            latestSessionAt: null | string;
        };
        /** Format: binary */
        IFormFile: string;
        LinePositionDto: {
            /** Format: date-time */
            time: string;
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
        };
        LoadDto: {
            /** Format: date-time */
            time: string;
            sensorName: string;
            /** Format: float */
            load: number | string;
        };
        MarkDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            /** Format: date */
            activeFrom: string;
            /** Format: date */
            activeUntil: null | string;
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
            description: null | string;
        };
        PatchRaceRequest: {
            /** Format: int32 */
            courseId: null | number | string;
            notes: null | string;
        };
        PatchSessionRequest: {
            /** Format: int32 */
            boatId: null | number | string;
            /** Format: int32 */
            courseId: null | number | string;
            notes: null | string;
        };
        PositionDto: {
            /** Format: date-time */
            time: string;
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
            /** Format: float */
            speedOverGround: number | string;
            /** Format: float */
            courseOverGround: number | string;
            /** Format: float */
            altitude: number | string;
            /** Format: float */
            quaternionW: number | string;
            /** Format: float */
            quaternionX: number | string;
            /** Format: float */
            quaternionY: number | string;
            /** Format: float */
            quaternionZ: number | string;
        };
        RaceDetailDto: {
            /** Format: int32 */
            raceNumber: number | string;
            /** Format: int32 */
            courseId: null | number | string;
            /** Format: date-time */
            countdownStartedAt: null | string;
            /** Format: int32 */
            countdownDurationSeconds: null | number | string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: null | string;
            /** Format: double */
            durationSeconds: null | number | string;
            /** Format: double */
            sailedDistanceMeters: number | string;
            /** Format: float */
            maxSpeedOverGround: number | string;
            notes: null | string;
            pinEnd: null | components["schemas"]["LinePositionDto"];
            boatEnd: null | components["schemas"]["LinePositionDto"];
            startAnalysis: null | components["schemas"]["StartAnalysisDto"];
        };
        RaceDto: {
            /** Format: int32 */
            raceNumber: number | string;
            /** Format: int32 */
            courseId: null | number | string;
            courseName: null | string;
            /** Format: date-time */
            countdownStartedAt: null | string;
            /** Format: int32 */
            countdownDurationSeconds: null | number | string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: null | string;
            /** Format: double */
            durationSeconds: null | number | string;
            /** Format: double */
            sailedDistanceMeters: number | string;
            /** Format: float */
            maxSpeedOverGround: number | string;
            notes: null | string;
        };
        RaceSummaryDto: {
            content: string;
            model: string;
            /** Format: date-time */
            generatedAt: string;
            isStale: boolean;
        };
        SailDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            /** Format: double */
            area: number | string;
        };
        SailRequest: {
            name: string;
            /** Format: double */
            area: number | string;
        };
        SessionDetailDto: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            boatId: null | number | string;
            boatName: null | string;
            /** Format: int32 */
            courseId: null | number | string;
            courseName: null | string;
            fileName: string;
            contentHash: string;
            /** Format: int16 */
            formatVersion: number | string;
            /** Format: int16 */
            telemetryRateHz: number | string;
            isFixedToBodyFrame: boolean;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            /** Format: date-time */
            uploadedAt: string;
            notes: null | string;
            races: components["schemas"]["RaceDto"][];
        };
        SessionSummaryDto: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            boatId: null | number | string;
            boatName: null | string;
            /** Format: int32 */
            courseId: null | number | string;
            courseName: null | string;
            fileName: string;
            /** Format: int16 */
            formatVersion: number | string;
            /** Format: int16 */
            telemetryRateHz: number | string;
            isFixedToBodyFrame: boolean;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt: string;
            /** Format: date-time */
            uploadedAt: string;
            notes: null | string;
            /** Format: int32 */
            raceCount: number | string;
        };
        ShiftAngleDto: {
            /** Format: date-time */
            time: string;
            isPort: boolean;
            isManual: boolean;
            /** Format: float */
            trueHeading: number | string;
            /** Format: float */
            speedOverGround: number | string;
        };
        SpeedThroughWaterDto: {
            /** Format: date-time */
            time: string;
            /** Format: float */
            forwardSpeed: number | string;
            /** Format: float */
            horizontalSpeed: number | string;
        };
        StartAnalysisDto: {
            /** Format: date-time */
            crossedAt: string;
            /** Format: double */
            timeBiasSeconds: null | number | string;
            /** Format: float */
            speedAtCrossingMs: number | string;
            /** Format: float */
            approachCourseDegrees: number | string;
            /** Format: double */
            lineFraction: number | string;
            isOcs: boolean;
            isOcsCleared: boolean;
            /** Format: double */
            ocsTimeBiasSeconds: null | number | string;
        };
        StartLineLengthDto: {
            /** Format: double */
            lengthMeters: number | string;
        };
        TemperatureDto: {
            /** Format: date-time */
            time: string;
            /** Format: float */
            temperature: number | string;
        };
        UpdateBoatClassRequest: {
            name: string;
            /** Format: double */
            lengthOverAll: null | number | string;
            /** Format: double */
            beam: null | number | string;
            /** Format: double */
            weight: null | number | string;
            /** Format: double */
            bowspritLength: null | number | string;
            sails: components["schemas"]["SailRequest"][];
        };
        UpdateBoatRequest: {
            name: string;
            sailNumber: null | string;
            /** Format: int32 */
            boatClassId: number | string;
            description: null | string;
        };
        UpdateCourseRequest: {
            name: string;
            /** Format: int32 */
            year: number | string;
            description: null | string;
            legs: components["schemas"]["CourseLegRequest"][];
        };
        UpdateMarkRequest: {
            name: string;
            /** Format: date */
            activeFrom: string;
            /** Format: date */
            activeUntil: null | string;
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
            description: null | string;
        };
        WindDto: {
            /** Format: date-time */
            time: string;
            /** Format: float */
            windDirection: number | string;
            /** Format: float */
            windSpeed: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
