// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vakaros.Vkx.Api.Data;

#nullable disable

namespace Vakaros.Vkx.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Boat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoatClass")
                        .HasColumnType("text")
                        .HasColumnName("boat_class");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SailNumber")
                        .HasColumnType("text")
                        .HasColumnName("sail_number");

                    b.HasKey("Id");

                    b.ToTable("boats", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.CourseLeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<string>("LegName")
                        .HasColumnType("text")
                        .HasColumnName("leg_name");

                    b.Property<int>("MarkId")
                        .HasColumnType("integer")
                        .HasColumnName("mark_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("MarkId");

                    b.ToTable("course_legs", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.DeclinationReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<float>("DeclinationOffset")
                        .HasColumnType("real")
                        .HasColumnName("declination_offset");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("declinations", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.DepthReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<float>("Depth")
                        .HasColumnType("real")
                        .HasColumnName("depth");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("depth_readings", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.LinePositionReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<short>("LineEnd")
                        .HasColumnType("smallint")
                        .HasColumnName("line_end");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("line_positions", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.LoadReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<float>("Load")
                        .HasColumnType("real")
                        .HasColumnName("load");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sensor_name");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("load_readings", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ActiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("active_from");

                    b.Property<DateOnly?>("ActiveUntil")
                        .HasColumnType("date")
                        .HasColumnName("active_until");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ActiveFrom")
                        .IsUnique();

                    b.ToTable("marks", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.PositionReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<float>("Altitude")
                        .HasColumnType("real")
                        .HasColumnName("altitude");

                    b.Property<float>("CourseOverGround")
                        .HasColumnType("real")
                        .HasColumnName("course_over_ground");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<float>("QuaternionW")
                        .HasColumnType("real")
                        .HasColumnName("quaternion_w");

                    b.Property<float>("QuaternionX")
                        .HasColumnType("real")
                        .HasColumnName("quaternion_x");

                    b.Property<float>("QuaternionY")
                        .HasColumnType("real")
                        .HasColumnName("quaternion_y");

                    b.Property<float>("QuaternionZ")
                        .HasColumnType("real")
                        .HasColumnName("quaternion_z");

                    b.Property<float>("SpeedOverGround")
                        .HasColumnType("real")
                        .HasColumnName("speed_over_ground");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<float>("MaxSpeedOverGround")
                        .HasColumnType("real")
                        .HasColumnName("max_speed_over_ground");

                    b.Property<int>("RaceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("race_number");

                    b.Property<double>("SailedDistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("sailed_distance_meters");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "RaceNumber")
                        .IsUnique();

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.RaceTimerEvent", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint")
                        .HasColumnName("event_type");

                    b.Property<int>("TimerValue")
                        .HasColumnType("integer")
                        .HasColumnName("timer_value");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("race_timer_events", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BoatId")
                        .HasColumnType("integer")
                        .HasColumnName("boat_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<short>("FormatVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("format_version");

                    b.Property<bool>("IsFixedToBodyFrame")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fixed_to_body_frame");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("TelemetryRateHz")
                        .HasColumnType("smallint")
                        .HasColumnName("telemetry_rate_hz");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("BoatId");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.ShiftAngleReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual");

                    b.Property<bool>("IsPort")
                        .HasColumnType("boolean")
                        .HasColumnName("is_port");

                    b.Property<float>("SpeedOverGround")
                        .HasColumnType("real")
                        .HasColumnName("speed_over_ground");

                    b.Property<float>("TrueHeading")
                        .HasColumnType("real")
                        .HasColumnName("true_heading");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("shift_angles", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.SpeedThroughWaterReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<float>("ForwardSpeed")
                        .HasColumnType("real")
                        .HasColumnName("forward_speed");

                    b.Property<float>("HorizontalSpeed")
                        .HasColumnType("real")
                        .HasColumnName("horizontal_speed");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("speed_through_water", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.TemperatureReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("temperature_readings", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.WindReading", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<float>("WindDirection")
                        .HasColumnType("real")
                        .HasColumnName("wind_direction");

                    b.Property<float>("WindSpeed")
                        .HasColumnType("real")
                        .HasColumnName("wind_speed");

                    b.HasKey("Time", "SessionId");

                    b.HasIndex("SessionId");

                    b.ToTable("wind_readings", (string)null);
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.CourseLeg", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Course", "Course")
                        .WithMany("Legs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Mark", "Mark")
                        .WithMany("CourseLegs")
                        .HasForeignKey("MarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Mark");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.DeclinationReading", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.DepthReading", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.LinePositionReading", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.LoadReading", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.PositionReading", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Race", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany("Races")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.RaceTimerEvent", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Session", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Boat", "Boat")
                        .WithMany("Sessions")
                        .HasForeignKey("BoatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Boat");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.ShiftAngleReading", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.SpeedThroughWaterReading", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.TemperatureReading", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.WindReading", b =>
                {
                    b.HasOne("Vakaros.Vkx.Api.Models.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Boat", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Course", b =>
                {
                    b.Navigation("Legs");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Mark", b =>
                {
                    b.Navigation("CourseLegs");
                });

            modelBuilder.Entity("Vakaros.Vkx.Api.Models.Entities.Session", b =>
                {
                    b.Navigation("Races");
                });
#pragma warning restore 612, 618
        }
    }
}
